#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# scripts/checkpoint_wrapup.sh
#
# Passive trigger: waits for the trained checkpoint to land, then runs the
# pretraining wrap-up pipeline and logs everything to checkpoint_wrapup.log.
#
# Steps (corrected vs. the original spec — see notes):
#   1. TorchScript export  → checkpoints/m2_final_ts.pt
#        Correct CLI is flag-based: --ckpt ... --out ...   (NOT positional).
#        The artifact is a fixed-shape, LOGITS-ONLY trace for edge latency.
#   2. Benchmark suite     → benchmarks/report.md   (benchmarks/run_all.py)
#   3. Service integration → docker image mtlnn:m2 with the EAGER checkpoint
#        baked in. NOTE: the server loads a state-dict checkpoint (embedded
#        config + model_state); a TorchScript file is NOT loadable by it, so
#        CKPT_PATH must point at the eager .pt, never the *_ts.pt artifact.
#        Step 3 is skipped (deferred) if the Docker daemon is not reachable.
#
# Run detached:
#     nohup bash scripts/checkpoint_wrapup.sh >/dev/null 2>&1 &
# ---------------------------------------------------------------------------
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || exit 99
LOG="$ROOT/checkpoint_wrapup.log"
CKPT="${CKPT:-checkpoints/m2_final.pt}"
TS_OUT="${TS_OUT:-checkpoints/m2_final_ts.pt}"
PYBIN="${PYBIN:-.venv/Scripts/python.exe}"
PORT="${PORT:-8001}"
MAX_ATTEMPTS="${MAX_ATTEMPTS:-2880}"   # 2880 x 60s = 48h ceiling
RETRY_SECS="${RETRY_SECS:-60}"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG"; }

[ -x "$PYBIN" ] || PYBIN="python"

log "==== checkpoint wrapup watcher started (pid $$); waiting for $CKPT ===="

# 0) Wait for the checkpoint file to appear.
found=0
for attempt in $(seq 1 "$MAX_ATTEMPTS"); do
  if [ -f "$CKPT" ]; then
    log "checkpoint detected on attempt ${attempt}: $CKPT"
    found=1
    break
  fi
  sleep "$RETRY_SECS"
done
if [ "$found" -ne 1 ]; then
  log "FAILED: checkpoint '$CKPT' never appeared within the time ceiling."
  exit 1
fi
sleep 5  # settle, in case the file is still being copied

# 1) TorchScript export (correct flag-based invocation).
log "step 1/3: TorchScript export -> $TS_OUT"
if "$PYBIN" scripts/export_torchscript.py --ckpt "$CKPT" --out "$TS_OUT" \
      --seq_len 256 --optimize --no_eager >>"$LOG" 2>&1; then
  log "step 1 OK ($TS_OUT)"
else
  log "step 1 FAILED (TorchScript export); see log above. Continuing."
fi

# 2) Benchmark suite -> benchmarks/report.md
log "step 2/3: benchmark suite -> benchmarks/report.md"
if "$PYBIN" benchmarks/run_all.py --ckpt "$CKPT" --out benchmarks/report.md >>"$LOG" 2>&1; then
  log "step 2 OK (benchmarks/report.md)"
else
  log "step 2 completed with failures (see benchmarks/report.md and log)."
fi

# 2.5) Reload the persistent public demo so it serves the trained weights.
# The demo (docker-compose.demo.yml) mounts ./checkpoints read-only and points
# CKPT_PATH at $CKPT; the model only loads at startup, so a restart is required
# to pick up the freshly-arrived checkpoint. Independent of docker.io.
if [ -f docker-compose.demo.yml ] && timeout 15 docker info >/dev/null 2>&1; then
  if docker ps --format '{{.Names}}' | grep -q '^mtlnn_demo$'; then
    log "step 2.5: reloading persistent demo (mtlnn_demo) to load $CKPT"
    if docker compose -f docker-compose.demo.yml restart >>"$LOG" 2>&1; then
      log "demo reloaded; now serving the trained checkpoint on :8088"
    else
      log "demo reload FAILED (see log above). Continuing."
    fi
  else
    log "step 2.5: persistent demo not running; skipping reload"
  fi
fi

# 3) Service integration: bake the EAGER checkpoint into a production image.
log "step 3/3: docker service integration (mtlnn:m2)"
if ! timeout 15 docker info >/dev/null 2>&1; then
  log "Docker daemon not reachable -> step 3 DEFERRED. After the daemon is up:"
  log "    docker build -t mtlnn ."
  log "    docker build -t mtlnn:m2 -f Dockerfile.m2 ."
  log "    docker run -d -p ${PORT}:8000 mtlnn:m2"
  log "==== wrapup DONE (steps 1-2 complete; step 3 deferred) ===="
  exit 0
fi

# Ensure the generic base image exists.
if ! docker image inspect mtlnn >/dev/null 2>&1; then
  log "base image 'mtlnn' missing; building it"
  docker build -t mtlnn . >>"$LOG" 2>&1 || { log "FAILED: base build"; exit 2; }
fi

# Derived image that bakes in the eager checkpoint + GPT-2 tokenizer.
# (Generated, not committed — keeps the base Dockerfile checkpoint-agnostic.)
cat > Dockerfile.m2 <<'DOCKER'
# Auto-generated by scripts/checkpoint_wrapup.sh — production image with the
# trained AwareLiquid-M2 checkpoint baked in. The server loads the EAGER
# state-dict checkpoint (NOT the TorchScript artifact).
FROM mtlnn
COPY checkpoints/m2_final.pt /app/checkpoints/m2_final.pt
ENV CKPT_PATH=/app/checkpoints/m2_final.pt \
    TOKENIZER=gpt2
DOCKER
log "wrote Dockerfile.m2"

if docker build -t mtlnn:m2 -f Dockerfile.m2 . >>"$LOG" 2>&1; then
  log "mtlnn:m2 build OK"
else
  log "FAILED: mtlnn:m2 build"; exit 3
fi

docker rm -f mtlnn_m2_verify >/dev/null 2>&1 || true
CID="$(docker run -d --name mtlnn_m2_verify -p "${PORT}:8000" mtlnn:m2 2>>"$LOG")"
log "mtlnn:m2 container started: ${CID:-<none>}"

ready=0
for i in $(seq 1 60); do
  if curl -sf "http://localhost:${PORT}/health" >/dev/null 2>&1; then ready=1; break; fi
  sleep 3
done
if [ "$ready" -eq 1 ]; then
  {
    echo "================ mtlnn:m2 VERIFICATION ================"
    echo "----- GET /v1/model -----"
    curl -s "http://localhost:${PORT}/v1/model"; echo
    echo "----- POST /v1/completions -----"
    curl -s -X POST "http://localhost:${PORT}/v1/completions" \
      -H "Content-Type: application/json" \
      -d '{"prompt":"Hello world","max_new_tokens":20,"do_sample":false}'; echo
    echo "======================================================"
  } >>"$LOG" 2>&1
  log "mtlnn:m2 endpoint verification complete"
else
  log "mtlnn:m2 /health never came up; dumping logs"
  docker logs mtlnn_m2_verify >>"$LOG" 2>&1
fi
docker rm -f mtlnn_m2_verify >/dev/null 2>&1 || true

log "==== checkpoint wrapup DONE (TorchScript + benchmarks + mtlnn:m2) ===="
exit 0
